import Foundation

/// The full reflection library: 210 quotes, 35 per category, authored
/// interleaved round-robin (scripture, saints, fatherhood, marriage,
/// leadership, virtue, repeat) so plain modulo day-selection naturally
/// rotates themes day to day. ReflectionMathTests enforces the count,
/// balance, and interleave — edit in whole rounds of six.
///
/// Sourcing: public-domain first (Douay-Rheims/KJV Scripture, saints in
/// PD translations, Chesterton pre-1929, stoics, American founders);
/// modern figures only as short attributed one-liners. Popular lines that
/// can't be verified are labeled "Attributed to …".
enum ReflectionQuotes {
    static let all: [ReflectionQuote] = [
        .init(id: "prov-22-6",
              text: "Train up a child in the way he should go: and when he is old, he will not depart from it.",
              attribution: "Proverbs 22:6", category: .scripture),
        .init(id: "augustine-restless",
              text: "Thou hast made us for Thyself, O Lord, and our heart is restless until it rests in Thee.",
              attribution: "St. Augustine", category: .saints),
        .init(id: "douglass-strong-children",
              text: "It is easier to build strong children than to repair broken men.",
              attribution: "Frederick Douglass", category: .fatherhood),
        .init(id: "eph-5-25",
              text: "Husbands, love your wives, as Christ also loved the church, and delivered himself up for it.",
              attribution: "Ephesians 5:25", category: .marriage),
        .init(id: "mark-10-43",
              text: "Whosoever will be great among you, shall be your minister: and whosoever of you will be the chiefest, shall be servant of all.",
              attribution: "Mark 10:43–44", category: .leadership),
        .init(id: "aurelius-fountain",
              text: "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.",
              attribution: "Marcus Aurelius", category: .virtue),

        .init(id: "josh-24-15",
              text: "As for me and my house, we will serve the Lord.",
              attribution: "Joshua 24:15", category: .scripture),
        .init(id: "augustine-pray-work",
              text: "Pray as though everything depended on God. Work as though everything depended on you.",
              attribution: "Attributed to St. Augustine", category: .saints),
        .init(id: "hesburgh-love-mother",
              text: "The most important thing a father can do for his children is to love their mother.",
              attribution: "Attributed to Fr. Theodore Hesburgh", category: .fatherhood),
        .init(id: "eccl-4-9",
              text: "Two are better than one… for if they fall, the one will lift up his fellow.",
              attribution: "Ecclesiastes 4:9–10", category: .marriage),
        .init(id: "luke-12-48",
              text: "Unto whomsoever much is given, of him shall be much required.",
              attribution: "Luke 12:48", category: .leadership),
        .init(id: "seneca-dare",
              text: "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.",
              attribution: "Seneca", category: .virtue),

        .init(id: "micah-6-8",
              text: "Do justly, and love mercy, and walk humbly with thy God.",
              attribution: "Micah 6:8", category: .scripture),
        .init(id: "kempis-judgement",
              text: "At the Day of Judgement we shall not be asked what we have read, but what we have done.",
              attribution: "Thomas à Kempis", category: .saints),
        .init(id: "kettering-example",
              text: "Every father should remember one day his son will follow his example, not his advice.",
              attribution: "Charles Kettering", category: .fatherhood),
        .init(id: "cor1-13-4",
              text: "Charity is patient, is kind: charity envieth not, dealeth not perversely, is not puffed up.",
              attribution: "1 Corinthians 13:4", category: .marriage),
        .init(id: "benedict-loved-not-feared",
              text: "Let him strive to be loved rather than feared.",
              attribution: "Rule of St. Benedict, on the abbot", category: .leadership),
        .init(id: "epictetus-opinions",
              text: "Men are disturbed not by the things which happen, but by the opinions about the things.",
              attribution: "Epictetus", category: .virtue),

        .init(id: "matt-5-16",
              text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
              attribution: "Matthew 5:16", category: .scripture),
        .init(id: "desales-patience-self",
              text: "Have patience with all things, but chiefly have patience with yourself.",
              attribution: "St. Francis de Sales", category: .saints),
        .init(id: "baldwin-imitate",
              text: "Children have never been very good at listening to their elders, but they have never failed to imitate them.",
              attribution: "James Baldwin", category: .fatherhood),
        .init(id: "song-3-4",
              text: "I found him whom my soul loveth.",
              attribution: "Song of Solomon 3:4", category: .marriage),
        .init(id: "aurelius-be-one",
              text: "Waste no more time arguing about what a good man should be. Be one.",
              attribution: "Marcus Aurelius", category: .leadership),
        .init(id: "roosevelt-arena",
              text: "It is not the critic who counts… The credit belongs to the man who is actually in the arena.",
              attribution: "Theodore Roosevelt", category: .virtue),

        .init(id: "matt-6-34",
              text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.",
              attribution: "Matthew 6:34", category: .scripture),
        .init(id: "desales-gentleness",
              text: "Nothing is so strong as gentleness, nothing so gentle as real strength.",
              attribution: "St. Francis de Sales", category: .saints),
        .init(id: "clark-good-man",
              text: "A father is a man who expects his son to be as good a man as he meant to be.",
              attribution: "Frank A. Clark", category: .fatherhood),
        .init(id: "sirach-26-1",
              text: "Happy is the husband of a good wife: for the number of his years is double.",
              attribution: "Sirach 26:1", category: .marriage),
        .init(id: "washington-no-excuse",
              text: "It is better to offer no excuse than a bad one.",
              attribution: "George Washington", category: .leadership),
        .init(id: "coolidge-persistence",
              text: "Nothing in this world can take the place of persistence. Persistence and determination alone are omnipotent.",
              attribution: "Calvin Coolidge", category: .virtue),

        .init(id: "matt-11-28",
              text: "Come to me, all you that labour, and are burdened, and I will refresh you.",
              attribution: "Matthew 11:28", category: .scripture),
        .init(id: "therese-small-sacrifice",
              text: "Miss no single opportunity of making some small sacrifice, here by a smiling look, there by a kindly word.",
              attribution: "St. Thérèse of Lisieux", category: .saints),
        .init(id: "battista-inheritance",
              text: "The best inheritance a parent can give his children is a few minutes of his time each day.",
              attribution: "O.A. Battista", category: .fatherhood),
        .init(id: "gen-2-18",
              text: "It is not good for man to be alone.",
              attribution: "Genesis 2:18", category: .marriage),
        .init(id: "franklin-well-done",
              text: "Well done is better than well said.",
              attribution: "Benjamin Franklin", category: .leadership),
        .init(id: "durant-habit",
              text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
              attribution: "Will Durant, summarizing Aristotle", category: .virtue),

        .init(id: "luke-16-10",
              text: "He that is faithful in that which is least, is faithful also in that which is greater.",
              attribution: "Luke 16:10", category: .scripture),
        .init(id: "teresa-avila-nothing-disturb",
              text: "Let nothing disturb thee; all things pass; God never changeth. Patience gains all things.",
              attribution: "St. Teresa of Ávila", category: .saints),
        .init(id: "fulghum-watching",
              text: "Don't worry that children never listen to you; worry that they are always watching you.",
              attribution: "Robert Fulghum", category: .fatherhood),
        .init(id: "sheen-three-to-love",
              text: "It takes three to make love, not two: you, your spouse, and God.",
              attribution: "Ven. Fulton J. Sheen", category: .marriage),
        .init(id: "lincoln-good-one",
              text: "Whatever you are, be a good one.",
              attribution: "Attributed to Abraham Lincoln", category: .leadership),
        .init(id: "ambrose-thanks",
              text: "No duty is more urgent than that of returning thanks.",
              attribution: "Attributed to St. Ambrose", category: .virtue),

        .init(id: "john-13-34",
              text: "A new commandment I give unto you, That ye love one another; as I have loved you.",
              attribution: "John 13:34", category: .scripture),
        .init(id: "ignatius-created",
              text: "Man is created to praise, reverence, and serve God our Lord.",
              attribution: "St. Ignatius of Loyola", category: .saints),
        .init(id: "jackson-presence",
              text: "Your children need your presence more than your presents.",
              attribution: "Jesse Jackson", category: .fatherhood),
        .init(id: "mclaughlin-falling",
              text: "A successful marriage requires falling in love many times, always with the same person.",
              attribution: "Mignon McLaughlin", category: .marriage),
        .init(id: "roosevelt-care",
              text: "People don't care how much you know until they know how much you care.",
              attribution: "Attributed to Theodore Roosevelt", category: .leadership),
        .init(id: "franklin-energy",
              text: "Energy and persistence conquer all things.",
              attribution: "Benjamin Franklin", category: .virtue),

        .init(id: "john-15-5",
              text: "I am the vine: you the branches… for without me you can do nothing.",
              attribution: "John 15:5", category: .scripture),
        .init(id: "benedict-idleness",
              text: "Idleness is the enemy of the soul.",
              attribution: "Rule of St. Benedict", category: .saints),
        .init(id: "roosevelt-household",
              text: "A household of children… makes all other forms of success and achievement lose their importance by comparison.",
              attribution: "Theodore Roosevelt", category: .fatherhood),
        .init(id: "dodds-think-together",
              text: "The goal in marriage is not to think alike, but to think together.",
              attribution: "Robert C. Dodds", category: .marriage),
        .init(id: "roosevelt-do-what-you-can",
              text: "Do what you can, with what you have, where you are.",
              attribution: "Theodore Roosevelt", category: .leadership),
        .init(id: "lincoln-prepare",
              text: "I will prepare and some day my chance will come.",
              attribution: "Attributed to Abraham Lincoln", category: .virtue),

        .init(id: "rom-12-12",
              text: "Rejoicing in hope. Patient in tribulation. Instant in prayer.",
              attribution: "Romans 12:12", category: .scripture),
        .init(id: "benedict-guests",
              text: "Let all guests who arrive be received like Christ.",
              attribution: "Rule of St. Benedict", category: .saints),
        .init(id: "anon-stoops",
              text: "No man stands so tall as when he stoops to help a child.",
              attribution: "Anonymous", category: .fatherhood),
        .init(id: "saintex-same-direction",
              text: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
              attribution: "Antoine de Saint-Exupéry", category: .marriage),
        .init(id: "greenleaf-servant-first",
              text: "The servant-leader is servant first.",
              attribution: "Robert K. Greenleaf", category: .leadership),
        .init(id: "emerson-do-the-thing",
              text: "Do the thing, and you shall have the power.",
              attribution: "Ralph Waldo Emerson", category: .virtue),

        .init(id: "rom-8-28",
              text: "All things work together for good to them that love God.",
              attribution: "Romans 8:28", category: .scripture),
        .init(id: "newman-definite-service",
              text: "God has created me to do Him some definite service; He has committed some work to me which He has not committed to another.",
              attribution: "St. John Henry Newman", category: .saints),
        .init(id: "jp2-family-nation",
              text: "As the family goes, so goes the nation and so goes the whole world in which we live.",
              attribution: "Pope St. John Paul II", category: .fatherhood),
        .init(id: "barth-grow-up",
              text: "Marriage is our last, best chance to grow up.",
              attribution: "Joseph Barth", category: .marriage),
        .init(id: "depree-define-reality",
              text: "The first responsibility of a leader is to define reality. The last is to say thank you.",
              attribution: "Max De Pree", category: .leadership),
        .init(id: "thoreau-dreams",
              text: "If one advances confidently in the direction of his dreams… he will meet with a success unexpected in common hours.",
              attribution: "Henry David Thoreau", category: .virtue),

        .init(id: "cor1-16-14",
              text: "Let all your things be done in charity.",
              attribution: "1 Corinthians 16:14", category: .scripture),
        .init(id: "chesterton-may-be-lost",
              text: "The way to love anything is to realize that it might be lost.",
              attribution: "G.K. Chesterton", category: .saints),
        .init(id: "francis-father-waits",
              text: "A good father knows how to wait and knows how to forgive from the depths of his heart.",
              attribution: "Pope Francis", category: .fatherhood),
        .init(id: "meurer-imperfect-couple",
              text: "A great marriage is not when the perfect couple comes together. It is when an imperfect couple learns to enjoy their differences.",
              attribution: "Dave Meurer", category: .marriage),
        .init(id: "drucker-right-things",
              text: "Management is doing things right; leadership is doing the right things.",
              attribution: "Peter Drucker", category: .leadership),
        .init(id: "churchill-continue",
              text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
              attribution: "Attributed to Winston Churchill", category: .virtue),

        .init(id: "gal-6-9",
              text: "Let us not be weary in well doing: for in due season we shall reap, if we faint not.",
              attribution: "Galatians 6:9", category: .scripture),
        .init(id: "chesterton-worth-doing-badly",
              text: "If a thing is worth doing, it is worth doing badly.",
              attribution: "G.K. Chesterton", category: .saints),
        .init(id: "prevost-masterpiece",
              text: "The heart of a father is the masterpiece of nature.",
              attribution: "Abbé Prévost", category: .fatherhood),
        .init(id: "tillich-listen",
              text: "The first duty of love is to listen.",
              attribution: "Paul Tillich", category: .marriage),
        .init(id: "drucker-culture-breakfast",
              text: "Culture eats strategy for breakfast.",
              attribution: "Attributed to Peter Drucker", category: .leadership),
        .init(id: "churchill-never-give-in",
              text: "Never give in — never, never, never, never, in nothing great or small, large or petty.",
              attribution: "Winston Churchill", category: .virtue),

        .init(id: "eph-4-32",
              text: "Be ye kind one to another, tenderhearted, forgiving one another.",
              attribution: "Ephesians 4:32", category: .scripture),
        .init(id: "chesterton-gratitude",
              text: "I would maintain that thanks are the highest form of thought, and that gratitude is happiness doubled by wonder.",
              attribution: "G.K. Chesterton", category: .saints),
        .init(id: "kelland-watch-him",
              text: "My father didn't tell me how to live; he lived, and let me watch him do it.",
              attribution: "Clarence B. Kelland", category: .fatherhood),
        .init(id: "chesterton-adventure",
              text: "Marriage is an adventure, like going to war.",
              attribution: "G.K. Chesterton", category: .marriage),
        .init(id: "jqa-inspire",
              text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.",
              attribution: "Attributed to John Quincy Adams", category: .leadership),
        .init(id: "keller-character",
              text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.",
              attribution: "Helen Keller", category: .virtue),

        .init(id: "phil-4-6",
              text: "Be nothing solicitous; but in every thing, by prayer and supplication, with thanksgiving, let your petitions be made known to God.",
              attribution: "Philippians 4:6", category: .scripture),
        .init(id: "aquinas-playful",
              text: "It is requisite for the relaxation of the mind that we make use, from time to time, of playful deeds and jokes.",
              attribution: "St. Thomas Aquinas", category: .saints),
        .init(id: "herbert-schoolmasters",
              text: "One father is more than a hundred schoolmasters.",
              attribution: "George Herbert", category: .fatherhood),
        .init(id: "weaver-choice",
              text: "Happily ever after is not a fairy tale. It's a choice.",
              attribution: "Fawn Weaver", category: .marriage),
        .init(id: "eisenhower-integrity",
              text: "The supreme quality for leadership is unquestionably integrity.",
              attribution: "Dwight D. Eisenhower", category: .leadership),
        .init(id: "btw-character",
              text: "Character, not circumstances, makes the man.",
              attribution: "Booker T. Washington", category: .virtue),

        .init(id: "phil-4-13",
              text: "I can do all things in him who strengtheneth me.",
              attribution: "Philippians 4:13", category: .scripture),
        .init(id: "vianney-your-public",
              text: "Do not try to please everybody. Try to please God, the angels, and the saints — they are your public.",
              attribution: "Attributed to St. John Vianney", category: .saints),
        .init(id: "johnson-memories",
              text: "To be in your children's memories tomorrow, you have to be in their lives today.",
              attribution: "Barbara Johnson", category: .fatherhood),
        .init(id: "laotzu-strength-courage",
              text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
              attribution: "Attributed to Lao Tzu", category: .marriage),
        .init(id: "powell-problems",
              text: "Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them.",
              attribution: "Colin Powell", category: .leadership),
        .init(id: "douglass-struggle",
              text: "If there is no struggle, there is no progress.",
              attribution: "Frederick Douglass", category: .virtue),

        .init(id: "col-3-23",
              text: "Whatsoever you do, do it from the heart, as to the Lord, and not to men.",
              attribution: "Colossians 3:23", category: .scripture),
        .init(id: "escriva-little-things",
              text: "Do everything for Love. Thus there will be no little things: everything will be big.",
              attribution: "St. Josemaría Escrivá", category: .saints),
        .init(id: "trainer-important-work",
              text: "Children are not a distraction from more important work. They are the most important work.",
              attribution: "Dr. John Trainer", category: .fatherhood),
        .init(id: "jp2-vocation-love",
              text: "Love is therefore the fundamental and innate vocation of every human being.",
              attribution: "Pope St. John Paul II", category: .marriage),
        .init(id: "sinek-in-your-charge",
              text: "Leadership is not about being in charge. It is about taking care of those in your charge.",
              attribution: "Simon Sinek", category: .leadership),
        .init(id: "rom-5-3",
              text: "Tribulation worketh patience; and patience, experience; and experience, hope.",
              attribution: "Romans 5:3–4", category: .virtue),

        .init(id: "james-1-19",
              text: "Let every man be swift to hear, slow to speak, slow to wrath.",
              attribution: "James 1:19", category: .scripture),
        .init(id: "teresa-small-things",
              text: "In this life we cannot do great things. We can only do small things with great love.",
              attribution: "St. Teresa of Calcutta", category: .saints),
        .init(id: "rubin-days-long",
              text: "The days are long, but the years are short.",
              attribution: "Gretchen Rubin", category: .fatherhood),
        .init(id: "francis-three-words",
              text: "In the family, three words need to be used: please, thank you, and sorry.",
              attribution: "Pope Francis", category: .marriage),
        .init(id: "meyer-hospitality",
              text: "Hospitality is present when something happens for you. It is absent when something happens to you.",
              attribution: "Danny Meyer", category: .leadership),
        .init(id: "heb-12-1",
              text: "Let us run with patience the race that is set before us.",
              attribution: "Hebrews 12:1", category: .virtue),

        .init(id: "ps-118-24",
              text: "This is the day which the Lord hath made; we will rejoice and be glad in it.",
              attribution: "Psalm 118:24", category: .scripture),
        .init(id: "teresa-one-person",
              text: "Never worry about numbers. Help one person at a time, and always start with the person nearest you.",
              attribution: "St. Teresa of Calcutta", category: .saints),
        .init(id: "swindoll-deposits",
              text: "Each day of our lives we make deposits in the memory banks of our children.",
              attribution: "Charles R. Swindoll", category: .fatherhood),
        .init(id: "signoret-threads",
              text: "Chains do not hold a marriage together. It is threads, hundreds of tiny threads, which sew people together through the years.",
              attribution: "Simone Signoret", category: .marriage),
        .init(id: "meyer-how-you-feel",
              text: "Business, like life, is all about how you make people feel. It's that simple, and it's that hard.",
              attribution: "Danny Meyer", category: .leadership),
        .init(id: "chesterton-inconvenience",
              text: "An inconvenience is only an adventure wrongly considered.",
              attribution: "G.K. Chesterton", category: .virtue),

        .init(id: "ps-46-10",
              text: "Be still, and know that I am God.",
              attribution: "Psalm 46:10", category: .scripture),
        .init(id: "jp2-open-doors",
              text: "Be not afraid. Open wide the doors for Christ.",
              attribution: "Pope St. John Paul II", category: .saints),
        .init(id: "anon-rich-man",
              text: "A truly rich man is one whose children run into his arms when his hands are empty.",
              attribution: "Anonymous", category: .fatherhood),
        .init(id: "maurois-conversation",
              text: "A happy marriage is a long conversation which always seems too short.",
              attribution: "André Maurois", category: .marriage),
        .init(id: "kelleher-people",
              text: "The business of business is people.",
              attribution: "Herb Kelleher", category: .leadership),
        .init(id: "lewis-courage",
              text: "Courage is not simply one of the virtues, but the form of every virtue at the testing point.",
              attribution: "C.S. Lewis", category: .virtue),

        .init(id: "ps-127-1",
              text: "Unless the Lord build the house, they labour in vain that build it.",
              attribution: "Psalm 127:1", category: .scripture),
        .init(id: "jp2-freedom-ought",
              text: "Freedom consists not in doing what we like, but in having the right to do what we ought.",
              attribution: "Pope St. John Paul II", category: .saints),
        .init(id: "omara-inner-voice",
              text: "The way we talk to our children becomes their inner voice.",
              attribution: "Peggy O'Mara", category: .fatherhood),
        .init(id: "winchell-beside-you",
              text: "Never above you. Never below you. Always beside you.",
              attribution: "Walter Winchell", category: .marriage),
        .init(id: "cathy-more-than-chicken",
              text: "We should be about more than just selling chicken. We should be a part of our customers' lives and the communities in which we serve.",
              attribution: "S. Truett Cathy", category: .leadership),
        .init(id: "frankl-change-ourselves",
              text: "When we are no longer able to change a situation, we are challenged to change ourselves.",
              attribution: "Viktor Frankl", category: .virtue),

        .init(id: "prov-3-5",
              text: "Trust in the Lord with all thine heart; and lean not unto thine own understanding.",
              attribution: "Proverbs 3:5", category: .scripture),
        .init(id: "sheen-clippings",
              text: "The proud man counts his newspaper clippings, the humble man his blessings.",
              attribution: "Ven. Fulton J. Sheen", category: .saints),
        .init(id: "beecher-parent-love",
              text: "There is no friendship, no love, like that of the parent for the child.",
              attribution: "Henry Ward Beecher", category: .fatherhood),
        .init(id: "hepburn-hold-onto",
              text: "The best thing to hold onto in life is each other.",
              attribution: "Audrey Hepburn", category: .marriage),
        .init(id: "kroc-people-you-hire",
              text: "You're only as good as the people you hire.",
              attribution: "Ray Kroc", category: .leadership),
        .init(id: "frank-improve-world",
              text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
              attribution: "Anne Frank", category: .virtue),

        .init(id: "prov-15-1",
              text: "A soft answer turneth away wrath: but grievous words stir up anger.",
              attribution: "Proverbs 15:1", category: .scripture),
        .init(id: "more-kings-servant",
              text: "I die the King's good servant, but God's first.",
              attribution: "St. Thomas More", category: .saints),
        .init(id: "fdr-prepare-children",
              text: "We may not be able to prepare the future for our children, but we can at least prepare our children for the future.",
              attribution: "Franklin D. Roosevelt", category: .fatherhood),
        .init(id: "browning-grow-old",
              text: "Grow old along with me! The best is yet to be.",
              attribution: "Robert Browning", category: .marriage),
        .init(id: "walton-self-esteem",
              text: "Outstanding leaders go out of their way to boost the self-esteem of their personnel.",
              attribution: "Sam Walton", category: .leadership),
        .init(id: "angelou-know-better",
              text: "Do the best you can until you know better. Then when you know better, do better.",
              attribution: "Maya Angelou", category: .virtue),

        .init(id: "prov-16-3",
              text: "Commit thy works unto the Lord, and thy thoughts shall be established.",
              attribution: "Proverbs 16:3", category: .scripture),
        .init(id: "pio-pray-hope",
              text: "Pray, hope, and don't worry.",
              attribution: "St. Padre Pio", category: .saints),
        .init(id: "rogers-play",
              text: "Play is often talked about as if it were a relief from serious learning. But for children, play is serious learning.",
              attribution: "Fred Rogers", category: .fatherhood),
        .init(id: "eliot-joined-for-life",
              text: "What greater thing is there for two human souls than to feel that they are joined for life?",
              attribution: "George Eliot", category: .marriage),
        .init(id: "carnegie-credit",
              text: "No man will make a great leader who wants to do it all himself or get all the credit for doing it.",
              attribution: "Andrew Carnegie", category: .leadership),
        .init(id: "confucius-slowly",
              text: "It does not matter how slowly you go as long as you do not stop.",
              attribution: "Attributed to Confucius", category: .virtue),

        .init(id: "prov-27-17",
              text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
              attribution: "Proverbs 27:17", category: .scripture),
        .init(id: "augustine-late-loved",
              text: "Late have I loved Thee, O Beauty ever ancient, ever new; late have I loved Thee.",
              attribution: "St. Augustine", category: .saints),
        .init(id: "unser-everything-he-knows",
              text: "Dad taught me everything I know. Unfortunately, he didn't teach me everything he knows.",
              attribution: "Al Unser", category: .fatherhood),
        .init(id: "anon-duet",
              text: "Marriage is a duet — when one sings, the other claps.",
              attribution: "Anonymous", category: .marriage),
        .init(id: "btw-lift-up",
              text: "If you want to lift yourself up, lift up someone else.",
              attribution: "Booker T. Washington", category: .leadership),
        .init(id: "proverb-fall-seven",
              text: "Fall seven times, stand up eight.",
              attribution: "Japanese proverb", category: .virtue),

        .init(id: "sirach-6-14",
              text: "A faithful friend is a strong defence: and he that hath found him, hath found a treasure.",
              attribution: "Sirach 6:14", category: .scripture),
        .init(id: "irenaeus-fully-alive",
              text: "The glory of God is man fully alive.",
              attribution: "St. Irenaeus", category: .saints),
        .init(id: "anon-messing-up",
              text: "Behind every great kid is a dad who's pretty sure he's messing it up.",
              attribution: "Anonymous", category: .fatherhood),
        .init(id: "brickner-right-mate",
              text: "Success in marriage does not come merely through finding the right mate, but through being the right mate.",
              attribution: "Barnett Brickner", category: .marriage),
        .init(id: "prov-16-32",
              text: "He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.",
              attribution: "Proverbs 16:32", category: .leadership),
        .init(id: "tim2-4-7",
              text: "I have fought a good fight, I have finished my course, I have kept the faith.",
              attribution: "2 Timothy 4:7", category: .virtue),

        .init(id: "matt-6-21",
              text: "For where your treasure is, there will your heart be also.",
              attribution: "Matthew 6:21", category: .scripture),
        .init(id: "catherine-world-on-fire",
              text: "Be who God meant you to be and you will set the world on fire.",
              attribution: "St. Catherine of Siena", category: .saints),
        .init(id: "chesterton-family-test",
              text: "The family is the test of freedom; because the family is the only thing that the free man makes for himself and by himself.",
              attribution: "G.K. Chesterton", category: .fatherhood),
        .init(id: "diller-stay-up",
              text: "Never go to bed mad. Stay up and fight.",
              attribution: "Phyllis Diller", category: .marriage),
        .init(id: "aurelius-swarm-bee",
              text: "That which is not good for the swarm, neither is it good for the bee.",
              attribution: "Marcus Aurelius", category: .leadership),
        .init(id: "aurelius-what-thou-hast",
              text: "Let not thy mind run on what thou lackest as much as on what thou hast already.",
              attribution: "Marcus Aurelius", category: .virtue),

        .init(id: "matt-7-12",
              text: "All things therefore whatsoever you would that men should do to you, do you also to them.",
              attribution: "Matthew 7:12", category: .scripture),
        .init(id: "kempis-be-not-angry",
              text: "Be not angry that you cannot make others as you wish them to be, since you cannot make yourself as you wish to be.",
              attribution: "Thomas à Kempis", category: .saints),
        .init(id: "chesterton-ordinary",
              text: "The most extraordinary thing in the world is an ordinary man and an ordinary woman and their ordinary children.",
              attribution: "G.K. Chesterton", category: .fatherhood),
        .init(id: "phelps-highest-happiness",
              text: "The highest happiness on earth is the happiness of marriage.",
              attribution: "William Lyon Phelps", category: .marriage),
        .init(id: "seneca-luck",
              text: "Luck is what happens when preparation meets opportunity.",
              attribution: "Attributed to Seneca", category: .leadership),
        .init(id: "seneca-nightly",
              text: "Every night before going to sleep, we must ask ourselves: what weakness did I overcome today? What virtue did I acquire?",
              attribution: "Seneca", category: .virtue),

        .init(id: "isa-40-31",
              text: "They that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles.",
              attribution: "Isaiah 40:31", category: .scripture),
        .init(id: "neri-cheerfulness",
              text: "Cheerfulness strengthens the heart and makes us persevere in a good life.",
              attribution: "St. Philip Neri", category: .saints),
        .init(id: "escriva-conduct",
              text: "Parents teach their children mainly through their own conduct.",
              attribution: "St. Josemaría Escrivá", category: .fatherhood),
        .init(id: "tertullian-two-christians",
              text: "How beautiful the marriage of two Christians: two who are one in hope, one in desire, one in the way of life they follow.",
              attribution: "Tertullian", category: .marriage),
        .init(id: "epictetus-say-then-do",
              text: "First say to yourself what you would be; and then do what you have to do.",
              attribution: "Epictetus", category: .leadership),
        .init(id: "holtz-carry-it",
              text: "It's not the load that breaks you down, it's the way you carry it.",
              attribution: "Lou Holtz", category: .virtue),

        .init(id: "deut-6-6",
              text: "These words which I command thee this day, shall be in thy heart: and thou shalt tell them to thy children.",
              attribution: "Deuteronomy 6:6–7", category: .scripture),
        .init(id: "newman-change-often",
              text: "To live is to change, and to be perfect is to have changed often.",
              attribution: "St. John Henry Newman", category: .saints),
        .init(id: "chrysostom-little-church",
              text: "Your home is a little Church.",
              attribution: "St. John Chrysostom", category: .fatherhood),
        .init(id: "anon-better-deal",
              text: "A good marriage is one where each partner secretly suspects they got the better deal.",
              attribution: "Anonymous", category: .marriage),
        .init(id: "wooden-activity",
              text: "Don't mistake activity for achievement.",
              attribution: "John Wooden", category: .leadership),
        .init(id: "carver-vision",
              text: "Where there is no vision, there is no hope.",
              attribution: "George Washington Carver", category: .virtue),

        .init(id: "eccl-3-1",
              text: "All things have their season, and in their times all things pass under heaven.",
              attribution: "Ecclesiastes 3:1", category: .scripture),
        .init(id: "chesterton-true-soldier",
              text: "The true soldier fights not because he hates what is in front of him, but because he loves what is behind him.",
              attribution: "G.K. Chesterton", category: .saints),
        .init(id: "anon-first-hero",
              text: "A dad is a son's first hero and a daughter's first love.",
              attribution: "Anonymous", category: .fatherhood),
        .init(id: "teresa-go-home",
              text: "What can you do to promote world peace? Go home and love your family.",
              attribution: "St. Teresa of Calcutta", category: .marriage),
        .init(id: "lombardi-measure",
              text: "The measure of who we are is what we do with what we have.",
              attribution: "Vince Lombardi", category: .leadership),
        .init(id: "earhart-decision-to-act",
              text: "The most difficult thing is the decision to act; the rest is merely tenacity.",
              attribution: "Amelia Earhart", category: .virtue),

        .init(id: "thess1-5-16",
              text: "Rejoice evermore. Pray without ceasing. In every thing give thanks.",
              attribution: "1 Thessalonians 5:16–18", category: .scripture),
        .init(id: "kolbe-indifference",
              text: "The most deadly poison of our times is indifference.",
              attribution: "St. Maximilian Kolbe", category: .saints),
        .init(id: "pearce-no-one-watching",
              text: "The greatest mark of a father is how he treats his children when no one is watching.",
              attribution: "Dan Pearce", category: .fatherhood),
        .init(id: "jones-ride-worthwhile",
              text: "Love doesn't make the world go round. Love is what makes the ride worthwhile.",
              attribution: "Franklin P. Jones", category: .marriage),
        .init(id: "john-13-14",
              text: "If I then, your Lord and Master, have washed your feet; ye also ought to wash one another's feet.",
              attribution: "John 13:14", category: .leadership),
        .init(id: "disney-begin-doing",
              text: "The way to get started is to quit talking and begin doing.",
              attribution: "Attributed to Walt Disney", category: .virtue),

        .init(id: "matt-25-21",
              text: "Well done, thou good and faithful servant… enter thou into the joy of thy lord.",
              attribution: "Matthew 25:21", category: .scripture),
        .init(id: "jerome-ignorance",
              text: "Ignorance of Scripture is ignorance of Christ.",
              attribution: "St. Jerome", category: .saints),
        .init(id: "landers-for-themselves",
              text: "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
              attribution: "Ann Landers", category: .fatherhood),
        .init(id: "youngman-secret",
              text: "The secret of a happy marriage remains a secret.",
              attribution: "Henny Youngman", category: .marriage),
        .init(id: "ziglar-help-others",
              text: "You will get all you want in life, if you help enough other people get what they want.",
              attribution: "Zig Ziglar", category: .leadership),
        .init(id: "parton-deeper-roots",
              text: "Storms make trees take deeper roots.",
              attribution: "Dolly Parton", category: .virtue),

        .init(id: "mark-10-45",
              text: "For even the Son of man came not to be ministered unto, but to minister.",
              attribution: "Mark 10:45", category: .scripture),
        .init(id: "liguori-trusts-god",
              text: "He who trusts himself is lost. He who trusts in God can do all things.",
              attribution: "St. Alphonsus Liguori", category: .saints),
        .init(id: "crudele-time",
              text: "Kids spell love T-I-M-E.",
              attribution: "John Crudele", category: .fatherhood),
        .init(id: "peter1-3-7",
              text: "Ye husbands, dwell with them according to knowledge, giving honour unto the wife… as being heirs together of the grace of life.",
              attribution: "1 Peter 3:7", category: .marriage),
        .init(id: "collins-good-enemy-great",
              text: "Good is the enemy of great.",
              attribution: "Jim Collins", category: .leadership),
        .init(id: "james-1-12",
              text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life.",
              attribution: "James 1:12", category: .virtue),

        .init(id: "prov-17-22",
              text: "A merry heart doeth good like a medicine.",
              attribution: "Proverbs 17:22", category: .scripture),
        .init(id: "frassati-getting-along",
              text: "To live without faith, without a heritage to defend, without battling constantly for truth, is not living but getting along.",
              attribution: "Bl. Pier Giorgio Frassati", category: .saints),
        .init(id: "francis-fathers-made",
              text: "Fathers are not born, but made. A man does not become a father simply by bringing a child into the world.",
              attribution: "Pope Francis", category: .fatherhood),
        .init(id: "viscott-sun-both-sides",
              text: "To love and be loved is to feel the sun from both sides.",
              attribution: "David Viscott", category: .marriage),
        .init(id: "escriva-supernatural-motive",
              text: "Add a supernatural motive to your ordinary work and you will have sanctified it.",
              attribution: "St. Josemaría Escrivá", category: .leadership),
        .init(id: "angelica-queasy",
              text: "Faith is one foot on the ground, one foot in the air, and a queasy feeling in the stomach.",
              attribution: "Mother Angelica", category: .virtue),
    ]
}
